name: Receive Morning Mail
on:
  issues:
    types:
      - opened

jobs:
  handle-issue:
    # Avoid spam issues
    if: ${{ github.event.issue.user.login }} == "fire-bot"
    runs-on: ubuntu-latest
    
    steps:
      - name: Print contents
        run: |
          echo "$CONTENT"
        env:
          CONTENT: ${{ github.event.issue.body }}

      - name: Close issue
        run: gh issue close "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
