name: Receive Morning Mail
on:
  issues:
    types:
      - opened

jobs:
  handle-issue:
    permissions:
      issues: write
      
    # Filter out non-email-generated issues
    if: ${{ github.event.issue.user.login }} == "fire-bot"
    runs-on: ubuntu-latest
    
    steps:
      - name: Install mdsplit
        run: |
          pip install mdsplit

      - name: Split markdown
        env:
          CONTENT: ${{ github.event.issue.body }}
        run: |
          echo "$CONTENT" > mm.md
          mdsplit -l 3 mm.md
          tree

      - name: Close issue
        run: gh issue close "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
