name: Receive Morning Mail
on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          CONTENT: ${{ github.event.issue.body }}
        run: |
          echo "$CONTENT"
