name: Receive Morning Mail
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      morning-mail

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "payload: ${{ toJson(github.event.client_payload) }}"
